### ISSUE TITLE
CSS Settings

### ISSUE THREAD

**Issue by Donovan2008** [spiritree/vue-orgchart#4]
Please help with setting the css selector. I'm unable to set line sizes, node colors and convert solid to dashed connection lines. 

Thank you

**Comment by spiritree** [comment]
line sizes and solid to dashed
```css
.orgchart tr.lines .topLine {
  border-top: 2px solid #616161; solid=>dashed
}
.orgchart tr.lines .rightLine {
  border-right: 1px solid #616161; solid=>dashed
}
.orgchart tr.lines .leftLine {
  border-left: 1px solid #616161; solid=>dashed
}
.orgchart tr.lines .downLine {
  width: 2px;
}
=>
.orgchart tr.lines .downLine {
  background-color: transparent;
  margin: 0 auto;
  height: 20px;
  width: 1px;
  border: 1px dashed #616161
  float: none;
}
```
node colors
```css
.orgchart .node .title {
  background-color: #42b983
}
```
